const adjectives = [
  "armer",
  "beiger",
  "blauer",
  "brauner",
  "bronzener",
  "dunkler",
  "edler",
  "feiger",
  "feindlicher",
  "ferner",
  "finsterer",
  "fremder",
  "freundlicher",
  "gelber",
  "gemeiner",
  "goldener",
  "grauer",
  "guter",
  "harter",
  "heller",
  "hoher",
  "junger",
  "kalter",
  "klarer",
  "kleiner",
  "kluger",
  "kurzer",
  "langer",
  "lauter",
  "leichter",
  "listiger",
  "mutiger",
  "naher",
  "neuer",
  "offener",
  "orangener",
  "purpurner",
  "rasender",
  "reicher",
  "roter",
  "ruhiger",
  "scharfer",
  "schneller",
  "schwarzer",
  "schwerer",
  "silberner",
  "starker",
  "stolzer",
  "tapferer",
  "tiefer",
  "treuer",
  "violetter",
  "weicher",
  "weiser",
  "weiter",
  "wilder",
];

const nouns = [
  "Vogel",
  "Adler",
  "Biber",
  "Tiger",
  "Luchs",
  "Falke",
  "Rabe",
  "Fuchs",
  "Wolf",
  "Hund",
  "Kater",
  "Bock",
  "Stier",
  "Hirsch",
  "Widder",
  "Bulle",
  "Hahn",
  "Karpfen",
  "Hecht",
  "Aal",
  "Loewe",
  "Panther",
  "Gepard",
  "Puma",
  "Bison",
  "Drache",
  "Greif",
  "Troll",
  "Ritter",
  "Held",
  "Knappe",
  "Kaiser",
  "Prinz",
  "Graf",
  "Baron",
  "Krieger",
  "Bauer",
  "Seemann",
  "Baum",
  "Berg",
  "Fluss",
  "Stern",
  "Mond",
  "Wind",
  "Himmel",
  "Start",
  "Anfang",
];

const specialChars = ["!", "?"];

export const generatePassword = (): string => {
  const adjective = adjectives[Math.floor(Math.random() * adjectives.length)];
  const noun = nouns[Math.floor(Math.random() * nouns.length)];
  const numbers = Math.floor(1000 + Math.random() * 9000).toString();
  const specialChar =
    specialChars[Math.floor(Math.random() * specialChars.length)];

  return `${adjective}${noun}${numbers}${specialChar}`;
};
